name: Build Debian loong64 live cd

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "59 12 * * *"
  workflow_dispatch:
jobs:
  debian:
    name: Build loong64 iso
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Install deps
        run: |
          sudo rm /etc/apt/sources.list
          sudo rm /etc/apt/sources.list.d/*
          cat > /etc/apt/sources.list << EOF
          # 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
          deb http://deb.debian.org/debian/ trixie main contrib non-free non-free-firmware
          # deb-src http://deb.debian.org/debian/ trixie main contrib non-free non-free-firmware

          deb http://deb.debian.org/debian/ trixie-updates main contrib non-free non-free-firmware
          # deb-src http://deb.debian.org/debian/ trixie-updates main contrib non-free non-free-firmware

          deb http://deb.debian.org/debian/ trixie-backports main contrib non-free non-free-firmware
          # deb-src http://deb.debian.org/debian/ trixie-backports main contrib non-free non-free-firmware

          # 以下安全更新软件源包含了官方源与镜像站配置，如有需要可自行修改注释切换
          deb https://security.debian.org/debian-security trixie-security main contrib non-free non-free-firmware
          # deb-src https://security.debian.org/debian-security trixie-security main contrib non-free non-free-firmware
          EOF
          sudo apt update
          sudo apt full-upgrade
          
      # PREFER_DOCKER=no ./compile.sh BOARD=uefi-loong64 BRANCH=current KERNEL_CONFIGURE=no DEB_COMPRESS=xz KERNEL_BTF=yes KERNEL_GIT=shallow RELEASE=sid EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no
      - name: Rebuild Armbian
        uses: armbian/build@v25.11.0-trunk.3
        with:
          armbian_target: ""
          armbian_kernel_branch: "current"
          armbian_release: "sid"
          armbian_board: "uefi-loong64"
          armbian_ui: "minimal"