name: Build Debian loong64 live cd

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "59 12 * * *"
  workflow_dispatch:
jobs:
  debian:
    name: Build loong64 iso
    runs-on: ubuntu-latest
    container:
      image: debian:trixie-backports
      options: --privileged=true
    permissions: write-all
    steps:
      - name: Install deps
        run: |
          apt update
          apt install jq sudo rsync build-essential wget curl git -y
      # PREFER_DOCKER=no ./compile.sh BOARD=uefi-loong64 BRANCH=current KERNEL_CONFIGURE=no DEB_COMPRESS=xz KERNEL_BTF=yes KERNEL_GIT=shallow RELEASE=sid EXPERT=yes BUILD_DESKTOP=no BUILD_MINIMAL=no
      - name: Rebuild Armbian
        uses: armbian/build@v25.11.0-trunk.3
        with:
          armbian_target: "image"
          armbian_kernel_branch: "current"
          armbian_release: "sid"
          armbian_board: "uefi-loong64"
          armbian_ui: "minimal"